name: lama5
channels:
  - defaults
  - conda-forge
dependencies:
  # - _libgcc_mutex
  # - _openmp_mutex
  # - absl-py
  # - aiohttp
  # - antlr-python-runtime
  # - async-timeout
  # - attrs
  # - blas
  # - blinker
  # - brotlipy
  # - bzip2
  # - c-ares
  # - ca-certificates
  # - cachetools
  # - certifi
  # - cffi
  # - chardet
  # - charset-normalizer
  # - click
  # - cloudpickle
  # - coverage
  # - cryptography
  - cudatoolkit
  # - cycler
  # - cython
  # - cytoolz
  # - dask-core
  # - dataclasses
  # - dbus
  # - decorator
  # - easydict
  # - expat
  # - ffmpeg
  # - fontconfig
  # - freetype
  # - fsspec
  # - future
  # - glib
  # - gmp
  # - gnutls
  # - google-auth
  # - google-auth-oauthlib
  # - grpcio
  # - gst-plugins-base
  # - gstreamer
  # - hydra-core
  # - icu
  # - idna
  # - idna_ssl
  - imageio
  # - importlib-metadata
  # - importlib_resources
  # - intel-openmp
  # - joblib
  - jpeg
  # - kiwisolver
  # - lame
  # - lcms2
  # - ld_impl_linux-64
  # - libblas
  # - libcblas
  # - libffi
  # - libgcc-ng
  # - libgfortran-ng
  # - libgfortran5
  # - libgomp
  # - libidn2
  # - liblapack
  # - libopus
  # - libpng
  # - libprotobuf
  # - libstdcxx-ng
  # - libtasn1
  # - libtiff
  # - libunistring
  # - libuuid
  # - libuv
  # - libvpx
  # - libwebp-base
  # - libxcb
  # - libxml2
  # - lz4-c
  # - markdown
  - matplotlib
  - matplotlib-base
  # - mkl
  # - multidict
  # - ncurses
  # - nettle
  # - networkx
  # - ninja
  - numpy
  # - oauthlib
  # - olefile
  # - omegaconf
  # - openh264
  # - openjpeg
  # - openssl
  # - packaging
  - pandas
  # - pcre
  - pillow
  - pip
  # - protobuf
  # - pyasn1
  # - pyasn1-modules
  # - pycparser
  # - pyjwt
  # - pyopenssl
  # - pyparsing
  # - pyqt
  # - pysocks
  - python
  # - python-dateutil
  # - python_abi
  # - pytz
  - pywavelets
  - pyyaml=5.4.1
  # - qt
  # - readline
  # - requests
  # - requests-oauthlib
  # - rsa
  - scikit-image
  - scikit-learn
  - scipy
  # - setuptools
  # - sip
  # - six
  # - sqlite
  # - tabulate
  - tensorboard
  - tensorboard-plugin-wit
  # - threadpoolctl
  # - tifffile
  # - tk
  # - toolz
  # - tqdm
  # - typing-extensions
  # - typing_extensions
  # - urllib3
  # - werkzeug
  # - wheel
  # - x264
  # - xz
  - yaml
  # - yarl
  # - zipp
  # - zlib
  # - zstd
  # - pip:
    # - albumentations
    # - braceexpand
    # - imgaug
    # - kornia
    # - opencv-python
    # - opencv-python-headless
    # - shapely
    # - webdataset
    # - wldhx-yadisk-direct
